version: '3.8'
services:
  db:
    image: mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS_ROOT}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./src/db:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
